title: Product
icon: 🍺
preset: page

fields:
  name:
    label: Beer Name
    type: text
  description:
    label: Beer Description
    type: textarea
    size: small
  stats:
    extends: fields/beers
    label: Beer Stats
